two_d_mode: true
frequency: 100.
sensor_timeout: 1.
map_frame: map
odom_frame: odom
base_link_frame: herb_base
world_frame: odom
odom0: odom
odom0_config: [
    false, false, false, # x, y, z
    false, false, false,  # roll, pitch, yaw
    true,  true, false, # x dot, y dot, z dot
    false, false, true, # roll dot, pitch dot, yaw dot
    false, false, false  # x ddot, y ddot, z ddot
]
