-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: ft_acceleration }
  - { name: ft_tare }
  - { name: bh_movehand }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_position, required: true }
  - { name: ft_tare }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: ft_wrench }
  - { name: ft_tare }
  - { name: bh_movehand }
-
  - { name: wam_position, required: true }
  - { name: wam_torque, required: true }
  - { name: bh_position, required: true }
  - { name: ft_tare }
