device: /dev/stargazer
fixed_frame_id: map
robot_frame_id: herb_base
stargazer_frame_id: stargazer_lens
marker_frame_prefix: stargazer/marker_
covariance: [
    0.08, 0.  , 0.  , 0.  , 0.  , 0.  ,
    0.  , 0.08, 0.  , 0.  , 0.  , 0.  , 
    0.  , 0.  , 0.08, 0.  , 0.  , 0.  ,
    0.  , 0.  , 0.  , 0.1, 0.  , 0.  ,
    0.  , 0.  , 0.  , 0.  , 0.10, 0.  ,
    0.  , 0.  , 0.  , 0.  , 0.  , 0.10
]
marker_map:
  '48':
  - [0.0, -1.0, 0.0, -0.435]
  - [1.0,  0.0, 0.0,  1.351]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
  '198':
  - [0.0, -1.0, 0.0, -1.656]
  - [1.0,  0.0, 0.0,  2.572]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
  '214':
  - [0.0, -1.0, 0.0, -1.654]
  - [1.0,  0.0, 0.0,  1.351]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
  '224':
  - [0.0, -1.0, 0.0, -0.436]
  - [1.0,  0.0, 0.0,  0.135]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
  '276':
  - [0.0, -1.0, 0.0,  0.784]
  - [1.0,  0.0, 0.0,  0.135]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
  '310':
  - [0.0, -1.0, 0.0,  0.783]
  - [1.0,  0.0, 0.0,  1.358]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
  '370':
  - [0.0, -1.0, 0.0, -0.437]
  - [1.0,  0.0, 0.0,  2.695]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
  '9414':
  - [0.0, -1.0, 0.0,  0.785]
  - [1.0,  0.0, 0.0,  2.706]
  - [0.0,  0.0, 1.0,  2.810]
  - [0.0,  0.0, 0.0,  1.0  ]
